baseURL = 'https://myblog.sudojoe.com'
languageCode = 'en-us'
title = 'JSG Blog'
theme = 'ananke'

[params]
  text_color = ""
  author = ""
  favicon = ""
  site_logo = ""
  description = "test"
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 4

[[params.ananke_socials]]
name = "github"
url = "https://github.com/impulsive-sudor"